### ISSUE TITLE
Page keeps refreshing on mobile

### ISSUE THREAD

**Issue by mushon** [akariv/speculatron#2]
It breaks the contribution flow that otherwise works quite well on mobile.
https://www.whatismybrowser.com/w/6CPL7W2

**Comment by akariv** [comment]
what are the reproduction steps?

**Comment by akariv** [comment]
Couldn't reproduce it on an iOS 15.5 simulator, let me know if this happens
again and exactly what was the flow prior.

**Comment by mushon** [comment]
It's not very consistent, I think the page crashes… could be maybe something having to do with the transition to #Y1986
Anyway, it may not have anything to do with the added features…

**Comment by mushon** [comment]
can't recreate
